{% set name = "pymedio" %}
{% set version = "0.2.14" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pymedio-{{ version }}.tar.gz
  sha256: 7fa1f7277c5b729a6d46e15ccb0249805a8d08a916378a5e658663aba4d295af

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6,<3.10
  run:
    - numpy >=1.22
    - python >=3.6,<3.10

test:
  imports:
    - pymedio
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jcreinhold/pymedio
  summary: read arbitrary medical images in python
  license: Apache-2.0
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - sarthakpati
